name: "Terraform code quality"

on:
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash
    working-directory: ./.terraform

jobs:
  code-quality:
    name: "Code quality"
    runs-on: ubuntu-latest
    environment: "Snowflake: KTB38830"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ vars.TERRAFORM_VERSION }}

      - name: "Terraform init"
        run: terraform init

      - name: "Terraform format"
        run: terraform fmt -check

      - name: "Terraform validate"
        run: terraform validate
